[package]
name = "conlaw"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = "1.14.0"
faer = "0.12.0"
faer-core = "0.12.0"
reborrow = "0.5.4"
thiserror = "1.0.49"
tracing = "0.1.37"

[dev-dependencies]
tracing-subscriber = "0.3.17"
